### ISSUE TITLE
Peer to Peer Code review

### ISSUE THREAD

**Issue by Gbengacode** [thecodechaser/thecodechaser-web-bootcamp#2]
Hi, Codechaser
You did a great job on your capstone project but there are some recommendations about this project you may consider: 

- `const tutors = [
  {
    image1: 'images/tiles.svg',
    image2: 'images/tutor.jpg',
    name: 'Ranjeet Singh',
    work: 'Bachlor from Teerthanker Mahaveer university',
    details:
      'Experienced in front end and backend development, teach students remotly using many tools.',
  },

  {
    image1: 'images/tiles.svg',
    image2: 'images/tutor.jpg',
    name: 'Ranjeet Singh',
    work: 'Bachlor from Teerthanker Mahaveer university',
    details:
      'Experienced in front end and backend development, teach students remotly using many tools.',
  },

  {
    image1: 'images/tiles.svg',
    image2: 'images/tutor.jpg',
    name: 'Ranjeet Singh',
    work: 'Bachlor from Teerthanker Mahaveer university',
    details:
      'Experienced in front end and backend development, teach students remotly using many tools.',
  },

  {
    image1: 'images/tiles.svg',
    image2: 'images/tutor.jpg',
    name: 'Ranjeet Singh',
    work: 'Bachlor from Teerthanker Mahaveer university',
    details:
      'Experienced in front end and backend development, teach students remotly using many tools.',
  },

  {
    image1: 'images/tiles.svg',
    image2: 'images/tutor.jpg',

-     name: 'Ranjeet Singh',

    work: 'Bachlor from Teerthanker Mahaveer university',
    details:
      'Experienced in front end and backend development, teach students remotly using many tools.',
  },

  {
    image1: 'images/tiles.svg',
    image2: 'images/tutor.jpg',
    name: 'Ranjeet Singh',
    work: 'Bachlor from Teerthanker Mahaveer university',
    details:
      'Experienced in front end and backend development, teach students remotly using many tools.',
  },
];`
You can separate this data file and import and also your loops. You are stating the index manually
 <h2 class="tutor-name">${tutors[0].name}</h2>

**Comment by thecodechaser** [comment]
> Hi, Codechaser You did a great job on your capstone project but there are some recommendations about this project you may consider:
> 
> * `const tutors = [
>   {
>   image1: 'images/tiles.svg',
>   image2: 'images/tutor.jpg',
>   name: 'Ranjeet Singh',
>   work: 'Bachlor from Teerthanker Mahaveer university',
>   details:
>   'Experienced in front end and backend development, teach students remotly using many tools.',
>   },
>   {
>   image1: 'images/tiles.svg',
>   image2: 'images/tutor.jpg',
>   name: 'Ranjeet Singh',
>   work: 'Bachlor from Teerthanker Mahaveer university',
>   details:
>   'Experienced in front end and backend development, teach students remotly using many tools.',
>   },
>   {
>   image1: 'images/tiles.svg',
>   image2: 'images/tutor.jpg',
>   name: 'Ranjeet Singh',
>   work: 'Bachlor from Teerthanker Mahaveer university',
>   details:
>   'Experienced in front end and backend development, teach students remotly using many tools.',
>   },
>   {
>   image1: 'images/tiles.svg',
>   image2: 'images/tutor.jpg',
>   name: 'Ranjeet Singh',
>   work: 'Bachlor from Teerthanker Mahaveer university',
>   details:
>   'Experienced in front end and backend development, teach students remotly using many tools.',
>   },
>   {
>   image1: 'images/tiles.svg',
>   image2: 'images/tutor.jpg',
> * ```
>   name: 'Ranjeet Singh',
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   work: 'Bachlor from Teerthanker Mahaveer university',
>   details:
>   'Experienced in front end and backend development, teach students remotly using many tools.',
>   },
>   {
>   image1: 'images/tiles.svg',
>   image2: 'images/tutor.jpg',
>   name: 'Ranjeet Singh',
>   work: 'Bachlor from Teerthanker Mahaveer university',
>   details:
>   'Experienced in front end and backend development, teach students remotly using many tools.',
>   },
>   ];`
>   You can separate this data file and import and also your loops. You are stating the index manually
> 
> ## ${tutors[0].name}

Hello @Gbengacode 👋 

Thank you for your feedback, I will implement these changes on my project to make it more improved.
